### ISSUE TITLE
How to convert activation fuctions to utilise SmeLu?

### ISSUE THREAD

**Issue by rllyryan** [ChristophReich1996/SmeLU#1]
Dear @ChristophReich1996,

Amazing work with the implementation of SmeLu!

This is not an issue but I a question as to how one will utilise the activation function.

```
class QNetwork(nn.Module):

    def __init__(self, action_dim, state_dim, hidden_dim):
        super(QNetwork, self).__init__()
        self.fc_1 = nn.Linear(state_dim, hidden_dim)
        self.fc_2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc_3 = nn.Linear(hidden_dim, action_dim)

    def forward(self, inp):
        
        x1 = F.leaky_relu(self.fc_1(inp))
        x1 = F.leaky_relu(self.fc_2(x1))
        x1 = self.fc_3(x1)

        return x1
```

Could I find out how does one use the SmeLu function here? The instantiation of the SmeLu function is tripping me a bit.

```
x1 = SmeLu(self.fc_1(inp))
```

^ and is this the correct way to use the function?

**Comment by ChristophReich1996** [comment]
Hi @rllyryan, 

Thanks for your interest! The implementation does only include an object-oriented implementation of the SmeLU activation. Meaning you must initialize the activation as an object first, as you do for initializing a linear layer in the constructor of your network, before using the activation in the forward pass.

```python
import torch
import torch.nn as nn
from smelu import SmeLU


class QNetwork(nn.Module):

    def __init__(self, action_dim: int, state_dim: int, hidden_dim: int) -> None:
        super(QNetwork, self).__init__()
        # Init linear layers
        self.fc_1 = nn.Linear(state_dim, hidden_dim)
        self.fc_2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc_3 = nn.Linear(hidden_dim, action_dim)
        # Init SmeLU activation
        self.act = SmeLU()

    def forward(self, inp: Tensor) -> Tensor:
        x1 = self.act(self.fc_1(inp))
        x1 = self.act(self.fc_2(x1))
        x1 = self.fc_3(x1)
        return x1
```
Note: Since the activation (`self.act`) does not hold any parameters (or any internal states/buffers) you can just initialize a single instance and use it anywhere you like.

Hope this helps :)
Christoph
